import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./_components/SessionWrapper";
import dbConnect from "@/lib/connectDB";
import ReduxProvider from "./_components/ReduxProvider";
import Navbar from "./_components/navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  dbConnect();
  return (
    <html lang="en">
      <ReduxProvider>
        <SessionWrapper>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
            <Navbar/>
            {children}
          </body>
        </SessionWrapper>
      </ReduxProvider>
    </html>
  );
}
